# Generated by Django 5.2.7 on 2025-11-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_studyspot_image_remove_studyspot_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyspot',
            name='image_url',
        ),
        migrations.AddField(
            model_name='studyspot',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studyspot',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyspot',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
