# Generated by Django 5.2.7 on 2025-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_studyspot_image_url_studyspot_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspot',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyspot',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
