# Generated by Django 5.2.7 on 2025-11-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_checkin_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspot',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
